#ifndef ACRCHIVEUTILS_GLOBAL_H
#define ACRCHIVEUTILS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ACRCHIVEUTILS_LIBRARY)
#  define ACRCHIVEUTILSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define ACRCHIVEUTILSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ACRCHIVEUTILS_GLOBAL_H
